package com.ski.shop.inventory.dto;

import com.ski.shop.inventory.domain.InventoryAlert;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * DTO for InventoryAlert entity operations
 */
public class InventoryAlertDto {

    public UUID alertId;
    public Long equipmentId;
    public InventoryAlert.AlertType alertType;
    public InventoryAlert.AlertSeverity severity;
    public InventoryAlert.AlertStatus status;
    public String title;
    public String message;
    public Integer thresholdValue;
    public Integer currentValue;
    public String assignedTo;
    public LocalDateTime acknowledgedAt;
    public String acknowledgedBy;
    public LocalDateTime resolvedAt;
    public String resolvedBy;
    public String resolutionNotes;
    public Boolean autoGenerated;
    public Boolean notificationSent;
    public LocalDateTime createdAt;
    public LocalDateTime updatedAt;

    // Helper properties
    public Boolean isActive;
    public Boolean isAcknowledged;
    public Boolean isResolved;
    public Boolean isHighPriority;

    public InventoryAlertDto() {}

    public InventoryAlertDto(InventoryAlert alert) {
        this.alertId = alert.alertId;
        this.equipmentId = alert.equipmentId;
        this.alertType = alert.alertType;
        this.severity = alert.severity;
        this.status = alert.status;
        this.title = alert.title;
        this.message = alert.message;
        this.thresholdValue = alert.thresholdValue;
        this.currentValue = alert.currentValue;
        this.assignedTo = alert.assignedTo;
        this.acknowledgedAt = alert.acknowledgedAt;
        this.acknowledgedBy = alert.acknowledgedBy;
        this.resolvedAt = alert.resolvedAt;
        this.resolvedBy = alert.resolvedBy;
        this.resolutionNotes = alert.resolutionNotes;
        this.autoGenerated = alert.autoGenerated;
        this.notificationSent = alert.notificationSent;
        this.createdAt = alert.createdAt;
        this.updatedAt = alert.updatedAt;

        // Set helper properties
        this.isActive = alert.isActive();
        this.isAcknowledged = alert.isAcknowledged();
        this.isResolved = alert.isResolved();
        this.isHighPriority = alert.isHighPriority();
    }

    /**
     * Request DTO for creating alerts
     */
    public static class CreateAlertRequest {
        public Long equipmentId;
        
        @NotNull
        public InventoryAlert.AlertType alertType;
        
        @NotNull
        public InventoryAlert.AlertSeverity severity;
        
        @NotNull
        public String title;
        
        @NotNull
        public String message;
        
        public Integer thresholdValue;
        public Integer currentValue;
        public String assignedTo;
        public Boolean autoGenerated = true;
    }

    /**
     * Request DTO for acknowledging alerts
     */
    public static class AcknowledgeAlertRequest {
        @NotNull
        public String userId;
    }

    /**
     * Request DTO for resolving alerts
     */
    public static class ResolveAlertRequest {
        @NotNull
        public String userId;
        
        public String resolutionNotes;
    }

    /**
     * Request DTO for dismissing alerts
     */
    public static class DismissAlertRequest {
        @NotNull
        public String userId;
    }

    /**
     * Response DTO for alert statistics
     */
    public static class AlertStatistics {
        public long totalAlerts;
        public long activeAlerts;
        public long acknowledgedAlerts;
        public long resolvedAlerts;
        public long criticalAlerts;
        public long highPriorityAlerts;
        public long lowStockAlerts;
        public long maintenanceAlerts;
        public long systemAlerts;
    }
}