package com.ski.shop.inventory.service;

import com.ski.shop.inventory.domain.InventoryAlert;
import com.ski.shop.inventory.domain.Equipment;
import com.ski.shop.inventory.dto.InventoryAlertDto;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.transaction.Transactional;
import io.quarkus.panache.common.Page;
import io.quarkus.panache.common.Sort;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Service for managing inventory alerts and notifications
 */
@ApplicationScoped
public class AlertService {

    /**
     * Create a new alert
     */
    @Transactional
    public InventoryAlertDto createAlert(InventoryAlertDto.CreateAlertRequest request) {
        InventoryAlert alert = new InventoryAlert();
        alert.equipmentId = request.equipmentId;
        alert.alertType = request.alertType;
        alert.severity = request.severity;
        alert.title = request.title;
        alert.message = request.message;
        alert.thresholdValue = request.thresholdValue;
        alert.currentValue = request.currentValue;
        alert.assignedTo = request.assignedTo;
        alert.autoGenerated = request.autoGenerated != null ? request.autoGenerated : true;

        alert.persist();

        return new InventoryAlertDto(alert);
    }

    /**
     * Get alert by ID
     */
    public Optional<InventoryAlertDto> getAlert(UUID alertId) {
        return InventoryAlert.find("alertId", alertId)
                .firstResultOptional()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert));
    }

    /**
     * Acknowledge an alert
     */
    @Transactional
    public Optional<InventoryAlertDto> acknowledgeAlert(UUID alertId, InventoryAlertDto.AcknowledgeAlertRequest request) {
        Optional<InventoryAlert> alertOpt = InventoryAlert.find("alertId", alertId)
                .firstResultOptional();
        
        if (alertOpt.isEmpty()) {
            return Optional.empty();
        }

        InventoryAlert alert = alertOpt.get();
        alert.acknowledge(request.userId);
        alert.persist();

        return Optional.of(new InventoryAlertDto(alert));
    }

    /**
     * Resolve an alert
     */
    @Transactional
    public Optional<InventoryAlertDto> resolveAlert(UUID alertId, InventoryAlertDto.ResolveAlertRequest request) {
        Optional<InventoryAlert> alertOpt = InventoryAlert.find("alertId", alertId)
                .firstResultOptional();
        
        if (alertOpt.isEmpty()) {
            return Optional.empty();
        }

        InventoryAlert alert = alertOpt.get();
        alert.resolve(request.userId, request.resolutionNotes);
        alert.persist();

        return Optional.of(new InventoryAlertDto(alert));
    }

    /**
     * Dismiss an alert
     */
    @Transactional
    public Optional<InventoryAlertDto> dismissAlert(UUID alertId, InventoryAlertDto.DismissAlertRequest request) {
        Optional<InventoryAlert> alertOpt = InventoryAlert.find("alertId", alertId)
                .firstResultOptional();
        
        if (alertOpt.isEmpty()) {
            return Optional.empty();
        }

        InventoryAlert alert = alertOpt.get();
        alert.dismiss(request.userId);
        alert.persist();

        return Optional.of(new InventoryAlertDto(alert));
    }

    /**
     * Get active alerts
     */
    public List<InventoryAlertDto> getActiveAlerts(int page, int size) {
        return InventoryAlert.find("status", Sort.descending("createdAt"), InventoryAlert.AlertStatus.ACTIVE)
                .page(Page.of(page, size))
                .list()
                .stream()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert))
                .collect(Collectors.toList());
    }

    /**
     * Get alerts by type
     */
    public List<InventoryAlertDto> getAlertsByType(InventoryAlert.AlertType alertType, int page, int size) {
        return InventoryAlert.find("alertType", Sort.descending("createdAt"), alertType)
                .page(Page.of(page, size))
                .list()
                .stream()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert))
                .collect(Collectors.toList());
    }

    /**
     * Get alerts by severity
     */
    public List<InventoryAlertDto> getAlertsBySeverity(InventoryAlert.AlertSeverity severity, int page, int size) {
        return InventoryAlert.find("severity", Sort.descending("createdAt"), severity)
                .page(Page.of(page, size))
                .list()
                .stream()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert))
                .collect(Collectors.toList());
    }

    /**
     * Get alerts for equipment
     */
    public List<InventoryAlertDto> getAlertsForEquipment(Long equipmentId, int page, int size) {
        return InventoryAlert.find("equipmentId", Sort.descending("createdAt"), equipmentId)
                .page(Page.of(page, size))
                .list()
                .stream()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert))
                .collect(Collectors.toList());
    }

    /**
     * Get critical alerts
     */
    public List<InventoryAlertDto> getCriticalAlerts() {
        return InventoryAlert.find("severity = ?1 AND status = ?2", 
                Sort.descending("createdAt"), 
                InventoryAlert.AlertSeverity.CRITICAL, 
                InventoryAlert.AlertStatus.ACTIVE)
                .list()
                .stream()
                .map(alert -> new InventoryAlertDto((InventoryAlert) alert))
                .collect(Collectors.toList());
    }

    /**
     * Create low stock alert
     */
    @Transactional
    public void createLowStockAlert(Long equipmentId, int currentStock, int threshold) {
        // Check if alert already exists for this equipment
        long existingAlerts = InventoryAlert.count(
            "equipmentId = ?1 AND alertType = ?2 AND status = ?3",
            equipmentId, InventoryAlert.AlertType.LOW_STOCK, InventoryAlert.AlertStatus.ACTIVE
        );
        
        if (existingAlerts > 0) {
            return; // Alert already exists
        }

        Equipment equipment = Equipment.findById(equipmentId);
        String equipmentName = equipment != null ? equipment.cachedName : "Unknown Equipment";

        InventoryAlertDto.CreateAlertRequest request = new InventoryAlertDto.CreateAlertRequest();
        request.equipmentId = equipmentId;
        request.alertType = InventoryAlert.AlertType.LOW_STOCK;
        request.severity = currentStock == 0 ? InventoryAlert.AlertSeverity.CRITICAL : InventoryAlert.AlertSeverity.HIGH;
        request.title = "Low Stock Alert - " + equipmentName;
        request.message = String.format("Stock level (%d) is below threshold (%d) for %s", 
                currentStock, threshold, equipmentName);
        request.thresholdValue = threshold;
        request.currentValue = currentStock;
        request.autoGenerated = true;

        createAlert(request);
    }

    /**
     * Create out of stock alert
     */
    @Transactional
    public void createOutOfStockAlert(Long equipmentId) {
        // Check if alert already exists for this equipment
        long existingAlerts = InventoryAlert.count(
            "equipmentId = ?1 AND alertType = ?2 AND status = ?3",
            equipmentId, InventoryAlert.AlertType.OUT_OF_STOCK, InventoryAlert.AlertStatus.ACTIVE
        );
        
        if (existingAlerts > 0) {
            return; // Alert already exists
        }

        Equipment equipment = Equipment.findById(equipmentId);
        String equipmentName = equipment != null ? equipment.cachedName : "Unknown Equipment";

        InventoryAlertDto.CreateAlertRequest request = new InventoryAlertDto.CreateAlertRequest();
        request.equipmentId = equipmentId;
        request.alertType = InventoryAlert.AlertType.OUT_OF_STOCK;
        request.severity = InventoryAlert.AlertSeverity.CRITICAL;
        request.title = "Out of Stock Alert - " + equipmentName;
        request.message = String.format("Equipment %s is completely out of stock", equipmentName);
        request.thresholdValue = 0;
        request.currentValue = 0;
        request.autoGenerated = true;

        createAlert(request);
    }

    /**
     * Create maintenance due alert
     */
    @Transactional
    public void createMaintenanceDueAlert(Long equipmentId, UUID maintenanceId, LocalDateTime scheduledDate) {
        Equipment equipment = Equipment.findById(equipmentId);
        String equipmentName = equipment != null ? equipment.cachedName : "Unknown Equipment";

        InventoryAlertDto.CreateAlertRequest request = new InventoryAlertDto.CreateAlertRequest();
        request.equipmentId = equipmentId;
        request.alertType = InventoryAlert.AlertType.MAINTENANCE_DUE;
        request.severity = InventoryAlert.AlertSeverity.MEDIUM;
        request.title = "Maintenance Due - " + equipmentName;
        request.message = String.format("Maintenance is scheduled for %s on %s", 
                equipmentName, scheduledDate.toLocalDate());
        request.autoGenerated = true;

        createAlert(request);
    }

    /**
     * Create maintenance overdue alert
     */
    @Transactional
    public void createMaintenanceOverdueAlert(Long equipmentId, UUID maintenanceId, LocalDateTime scheduledDate) {
        Equipment equipment = Equipment.findById(equipmentId);
        String equipmentName = equipment != null ? equipment.cachedName : "Unknown Equipment";

        InventoryAlertDto.CreateAlertRequest request = new InventoryAlertDto.CreateAlertRequest();
        request.equipmentId = equipmentId;
        request.alertType = InventoryAlert.AlertType.MAINTENANCE_OVERDUE;
        request.severity = InventoryAlert.AlertSeverity.HIGH;
        request.title = "Maintenance Overdue - " + equipmentName;
        request.message = String.format("Maintenance for %s was scheduled for %s and is now overdue", 
                equipmentName, scheduledDate.toLocalDate());
        request.autoGenerated = true;

        createAlert(request);
    }

    /**
     * Create sync failure alert
     */
    @Transactional
    public void createSyncFailureAlert(String errorMessage, String details) {
        InventoryAlertDto.CreateAlertRequest request = new InventoryAlertDto.CreateAlertRequest();
        request.alertType = InventoryAlert.AlertType.SYNC_FAILURE;
        request.severity = InventoryAlert.AlertSeverity.HIGH;
        request.title = "Inventory Sync Failure";
        request.message = "Failed to synchronize inventory data: " + errorMessage + 
                (details != null ? " Details: " + details : "");
        request.autoGenerated = true;

        createAlert(request);
    }

    /**
     * Check and create stock alerts for all equipment
     */
    @Transactional
    public void checkStockLevelsAndCreateAlerts() {
        List<Equipment> equipmentList = Equipment.listAll();
        
        for (Equipment equipment : equipmentList) {
            int lowStockThreshold = 5; // Configurable threshold
            
            if (equipment.availableQuantity == 0) {
                createOutOfStockAlert(equipment.id);
            } else if (equipment.availableQuantity <= lowStockThreshold) {
                createLowStockAlert(equipment.id, equipment.availableQuantity, lowStockThreshold);
            }
        }
    }

    /**
     * Get alert statistics
     */
    public InventoryAlertDto.AlertStatistics getAlertStatistics() {
        InventoryAlertDto.AlertStatistics stats = new InventoryAlertDto.AlertStatistics();
        
        stats.totalAlerts = InventoryAlert.count();
        stats.activeAlerts = InventoryAlert.count("status", InventoryAlert.AlertStatus.ACTIVE);
        stats.acknowledgedAlerts = InventoryAlert.count("status", InventoryAlert.AlertStatus.ACKNOWLEDGED);
        stats.resolvedAlerts = InventoryAlert.count("status", InventoryAlert.AlertStatus.RESOLVED);
        stats.criticalAlerts = InventoryAlert.count("severity = ?1 AND status = ?2", 
                InventoryAlert.AlertSeverity.CRITICAL, InventoryAlert.AlertStatus.ACTIVE);
        stats.highPriorityAlerts = InventoryAlert.count("severity = ?1 AND status = ?2", 
                InventoryAlert.AlertSeverity.HIGH, InventoryAlert.AlertStatus.ACTIVE);
        stats.lowStockAlerts = InventoryAlert.count("alertType = ?1 AND status = ?2", 
                InventoryAlert.AlertType.LOW_STOCK, InventoryAlert.AlertStatus.ACTIVE);
        stats.maintenanceAlerts = InventoryAlert.count("alertType IN (?1, ?2) AND status = ?3", 
                InventoryAlert.AlertType.MAINTENANCE_DUE, InventoryAlert.AlertType.MAINTENANCE_OVERDUE, 
                InventoryAlert.AlertStatus.ACTIVE);
        stats.systemAlerts = InventoryAlert.count("alertType IN (?1, ?2, ?3) AND status = ?4", 
                InventoryAlert.AlertType.SYNC_FAILURE, InventoryAlert.AlertType.SYSTEM_ERROR, 
                InventoryAlert.AlertType.PERFORMANCE_ISSUE, InventoryAlert.AlertStatus.ACTIVE);
        
        return stats;
    }

    /**
     * Clean up old resolved alerts (older than specified days)
     */
    @Transactional
    public long cleanupOldAlerts(int daysOld) {
        LocalDateTime cutoffDate = LocalDateTime.now().minusDays(daysOld);
        return InventoryAlert.delete("status = ?1 AND resolvedAt < ?2", 
                InventoryAlert.AlertStatus.RESOLVED, cutoffDate);
    }
}