package com.ski.shop.inventory.domain;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * InventoryAlert entity for tracking inventory-related alerts and notifications.
 * Supports various alert types including low stock, maintenance due, and system alerts.
 */
@Entity
@Table(name = "inventory_alerts", indexes = {
    @Index(name = "idx_alert_equipment_id", columnList = "equipment_id"),
    @Index(name = "idx_alert_type", columnList = "alert_type"),
    @Index(name = "idx_alert_severity", columnList = "severity"),
    @Index(name = "idx_alert_status", columnList = "status"),
    @Index(name = "idx_alert_created_at", columnList = "created_at")
})
public class InventoryAlert extends PanacheEntity {

    @NotNull
    @Column(name = "alert_id", nullable = false, unique = true)
    public UUID alertId = UUID.randomUUID();

    @Column(name = "equipment_id")
    public Long equipmentId;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_type", nullable = false)
    public AlertType alertType;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false)
    public AlertSeverity severity;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    public AlertStatus status = AlertStatus.ACTIVE;

    @Column(name = "title", length = 255, nullable = false)
    public String title;

    @Column(name = "message", length = 1000, nullable = false)
    public String message;

    @Column(name = "threshold_value")
    public Integer thresholdValue;

    @Column(name = "current_value")
    public Integer currentValue;

    @Column(name = "assigned_to", length = 100)
    public String assignedTo;

    @Column(name = "acknowledged_at")
    public LocalDateTime acknowledgedAt;

    @Column(name = "acknowledged_by", length = 100)
    public String acknowledgedBy;

    @Column(name = "resolved_at")
    public LocalDateTime resolvedAt;

    @Column(name = "resolved_by", length = 100)
    public String resolvedBy;

    @Column(name = "resolution_notes", length = 1000)
    public String resolutionNotes;

    @Column(name = "auto_generated", nullable = false)
    public Boolean autoGenerated = true;

    @Column(name = "notification_sent", nullable = false)
    public Boolean notificationSent = false;

    @Version
    @Column(name = "version_field")
    public Long versionField = 1L;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false)
    public LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    public LocalDateTime updatedAt;

    // Helper methods
    public boolean isActive() {
        return status == AlertStatus.ACTIVE;
    }

    public boolean isAcknowledged() {
        return acknowledgedAt != null;
    }

    public boolean isResolved() {
        return status == AlertStatus.RESOLVED;
    }

    public boolean isHighPriority() {
        return severity == AlertSeverity.CRITICAL || severity == AlertSeverity.HIGH;
    }

    public void acknowledge(String userId) {
        this.acknowledgedAt = LocalDateTime.now();
        this.acknowledgedBy = userId;
        this.status = AlertStatus.ACKNOWLEDGED;
    }

    public void resolve(String userId, String resolutionNotes) {
        this.resolvedAt = LocalDateTime.now();
        this.resolvedBy = userId;
        this.resolutionNotes = resolutionNotes;
        this.status = AlertStatus.RESOLVED;
    }

    public void dismiss(String userId) {
        this.status = AlertStatus.DISMISSED;
        this.resolvedAt = LocalDateTime.now();
        this.resolvedBy = userId;
    }

    public enum AlertType {
        LOW_STOCK,
        OUT_OF_STOCK,
        MAINTENANCE_DUE,
        MAINTENANCE_OVERDUE,
        EQUIPMENT_MALFUNCTION,
        RESERVATION_EXPIRING,
        SYNC_FAILURE,
        SYSTEM_ERROR,
        PERFORMANCE_ISSUE,
        SECURITY_ALERT
    }

    public enum AlertSeverity {
        LOW,
        MEDIUM,
        HIGH,
        CRITICAL
    }

    public enum AlertStatus {
        ACTIVE,
        ACKNOWLEDGED,
        RESOLVED,
        DISMISSED
    }
}